### PR TITLE
Fix TG_OWT_PACKAGED_BUILD switch with TG_OWT_DLOPEN_PIPEWIRE=ON

### PR DESCRIPTION
**Pull request by mymedia2**

### CODE REVIEW

**Comment by ilya-fedin** [comment]
You don't really fix it. link_pipewire will link the library without dlopen in mind.

**Comment by ilya-fedin** [comment]
Why are you doing that, pipewire 0.2.x is outdated

**Comment by john-preston** [comment]
@mymedia2 What about the link_pipewire? Should this be fixed and merged after?

**Review by john-preston — CHANGES_REQUESTED** [review]
Please provide a fix for the "link_pipewire" call together with "dlopen" way.

**Pull request closed without merging**
