### PR TITLE
Fix build on FreeBSD

### PR DESCRIPTION
**Pull request by osokin**

### CODE REVIEW

**Comment by ilya-fedin** [comment]
Doesn't #136 do the same thing?

**Comment by osokin** [comment]
Seems like related, haven't test that yet.

**Comment by klemensn** [comment]
> Doesn't #136 do the same thing?

Yes, except I don't guard the includes with OS headers -- they should work everywhere.

**Comment by klemensn** [comment]
> Doesn't #136 do the same thing?

Got in already, so this PR is obsolete now.

**Pull request closed without merging**
