### PR TITLE
Fix compilation with clang>=12; fixes #83

### LINKED ISSUE #83: Build error with clang-13
```
/var/tmp/portage/media-libs/tg_owt-0_pre20211207/work/tg_owt-d5c3d43b959c7e9e7d8004b9b7fdadd12ce7d589/src/modules/congestion_controller/goog_cc/loss_based_bwe_v2.cc:288:10: error: no matching member function for call to 'emplace'
  config.emplace();
  ~~~~~~~^~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/g++-v11/optional:868:2: note: candidate template ignored: requirement 'is_constructible_v<webrtc::LossBasedBweV2::Config>' was not satisfied [with _Args = <>]
        emplace(_Args&&... __args)
        ^
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/g++-v11/optional:879:2: note: candidate function template not viable: requires at least argument '__il', but no arguments were provided
        emplace(initializer_list<_Up> __il, _Args&&... __args)
        ^
1 error generated.
```

I'm not sure how to even begin solving this, nor why it was introduced in this version of clang.

https://bugs.gentoo.org/830845

### PR DESCRIPTION
**Pull request by msva**

### CODE REVIEW

**Comment by ilya-fedin** [comment]
GH doesn't detect "Fixes" in the title it seems (either in the commit or in the PR), so it should be moved to a separate line in the commit message and to PR description for the title

**Comment by msva** [comment]
> GH doesn't detect "Fixes" in the title it seems

Why do you think that?

It works in my other repos for ages already :shrug:

**Comment by ilya-fedin** [comment]
изображение

**Comment by john-preston** [comment]
@msva Is it OK in current code without this PR?

**Comment by klemensn** [comment]
> @msva Is it OK in current code without this PR?

Should be, since https://cgit.freebsd.org/ports/tree/net-im/tg_owt/ neither pulls this PR nor includes it as a local patch.

Same on OpenBSD, using Clang 16.0.6.

**Comment by john-preston** [comment]
@msva

Can you please:

1. Add "Patch: " prefix to the commit message (so it's easier to migrate it to a newer version of WebRTC code).
2. Change it to `Config() = default;` and check if that helpers or if it is required to fix the way you did right now?

**Comment by john-preston** [comment]
Ok, nevermind, the second is said to be "no", so I'll deal with the first one some day later.

**Comment by john-preston** [comment]
Thanks!

**Pull request merged**
