### PR TITLE
Defer third-party source handling to when it is needed

### PR DESCRIPTION
**Pull request by klemensn**
Using GitHub's autogenerated source tarballs to build tg_owt requires
OS package maintainers to fetch third-party software by other means as
they are git submodules and thus not included.

In the case of `TG_OWT_PACKAGED_BUILD=1`, third-party bundles are only
needed if the system's respective package could not be found.

On OpenBSD, tg_owt is built with `TG_OWT_PACKAGED_BUILD=1` and abseil,
crc3232, libopenh264, libusrsctp and libvpx are used from packages.

Thus only libvpx must be fetched and built as bundle.

However, cmake currently expects all third-party sources to be present,
otherwise the `cmake/*.cmake` files fail in referencing nonexistent
C/C++ source files.

In packaged builds, neither the sources, nor the defined `tg_owt::*`
targets are required iff packages were found, i.e. `*_FOUND=1`.

Defer third-party source handling to when it is actually needed to fix
the build and/or avoid needless fetching of source files.

Tested on OpenBSD where I previously just removed all irrelevant
`include(cmake/lib*.cmake)` lines to unbreak the packaged build.

### CODE REVIEW

**Comment by klemensn** [comment]
This is the same approach done in https://github.com/desktop-app/tg_owt/pull/76 except that it follows through for all dependencies and not just abseil-cpp.

**Comment by ilya-fedin** [comment]
> Unexpectedly, the following does _not_ work, i.e. `*_FOUND` stay
> undefined when used immediately after `include(cmake/external.cmake)`:

That's expected since the functions from external.cmake aren't called yet

**Comment by klemensn** [comment]
> > Unexpectedly, the following does _not_ work, i.e. `*_FOUND` stay
> > undefined when used immediately after `include(cmake/external.cmake)`:
> 
> That's expected since the functions from external.cmake aren't called yet

Right, thanks for pointing out the ovious.

**Comment by ilya-fedin** [comment]
Unfortunately, this PR breaks snap build
https://github.com/ilya-fedin/tdesktop/runs/4833559924?check_suite_focus=true

**Comment by klemensn** [comment]
I still haven't found the time and energy to dig into what the Linux build is really doing...

Meanwhile, the commit has been rebased after conflicts with the recent libvpx changes.

**Comment by ilya-fedin** [comment]
Maybe close the PR and re-open when you solve the problem?

**Comment by klemensn** [comment]
Rebased after OpenH264 changes.

**Comment by ilya-fedin** [comment]
Why do you move the include directives rather than just adding conditions? That changes the order of logic and looks weirdly as includes are usually done at the top of a file.

**Comment by ilya-fedin** [comment]
Never mind, I see

**Comment by ilya-fedin** [comment]
I tried to run your PR on the CI again but it still fails with snap: https://github.com/ilya-fedin/tdesktop/actions/runs/10134963634/job/28021803630

I suspect this could be because master branch on your repo is outdated.

**Comment by ilya-fedin** [comment]
Good news

**Comment by klemensn** [comment]
> Good news

Time to merge it!

**Comment by klemensn** [comment]
If this goes in and #137 is good to go, too, I'd amend this PR to account for `libsrtp.cmake` as well.

**Comment by john-preston** [comment]
@klemensn can you please indent the added lines like the next ones are?

**Comment by john-preston** [comment]
Can you please add a "CMake: " prefix to the commit message so that it's easy to skip cherry picking the build configuration changes when I update webrtc code next time?

**Comment by klemensn** [comment]
> Can you please add a "CMake: " prefix to the commit message so that it's easy to skip cherry picking the build configuration changes when I update webrtc code next time?

Sure, done.

**Pull request merged**
