### PR TITLE
Add missing ARM sources to cmake

### PR DESCRIPTION
**Pull request by gasinvein**
Fixes Linux ARM build after the source update.

### CODE REVIEW

**Comment by overtake** [comment]
I have already added this to another branch. Look at desktop_caprurer+arm

**Comment by gasinvein** [comment]
@overtake Oh. Should I close it, then? Any ETA for your changes to land in master branch?

**Comment by overtake** [comment]
Better ask @preston

**Comment by preston** [comment]
You have the wrong guy.

**Comment by john-preston** [comment]
I hope it is fine on the latest master.

**Comment by gasinvein** [comment]
Works with latest master, thanks.

**Pull request closed without merging**
