### PR TITLE
fix(h265_pps_parser): fix missing cstdint include

### PR DESCRIPTION
**Pull request by Xiretza**

### CODE REVIEW

**Review by rakino — APPROVED** [review]

**Comment by mid-kid** [comment]
Bumping this issue as it's a rather important fix.

**Comment by ilya-fedin** [comment]
I think I was sending link to this PR multiple times to preston, but every time he ignored my messages.

**Comment by ilya-fedin** [comment]
@mid-kid preston said he won't merge this at least unless the code is updated to M108. Maybe this won't be needed then.

**Comment by mid-kid** [comment]
That is kind of silly for a one-line change merged at the click of a button. Heck for all we know you'll start hitting this issue in some build environments eventually too.
Oh well, do what you want, it doesn't really matter.

**Comment by ilya-fedin** [comment]
> Heck for all we know you'll start hitting this issue in some build environments eventually too.

I don't think this will happen in near two years as CentOS 7 doesn't have newer compilers (and we can't update to a newer OS as that would mean deprecating older ones, thanks glibc, this is not something preston wants to do), flatpak couldn't be updated to a newer runtime as calls are broken with openssl 3 and snap's core24 runtime will out in 2024. And even then we can stick to core22.

> Oh well, do what you want, we'll just keep carrying the patch then...

Relax, is it really so important? This PR is here for half of a year, can't you wait a little bit more? :thinking: 
As you said, it's an one-line change, it shouldn't be hard to have it for a while given that it seems it's already in your patchset.

**Comment by mid-kid** [comment]
I realize my previous comment may have been a little rash, it wasn't meant like that, so sorry for that.
My main concern with getting patches like this merged is reducing duplication of effort when packaging or upgrading the compiler on an existing package. It's always annoying to have to scour for bug trackers or other distribution's patches. It's a minor inconvenience to carry patches like this, but we'd just rather not if we don't have to

**Comment by ilya-fedin** [comment]
@mid-kid M108 code is in m108 branch and tdesktop on dev branch is migrated to it, you can try to build and see whether this patch is still needed

**Comment by mid-kid** [comment]
Webrtc upgrades are generally a mess from our side, and I'll need a bit to test the various combinations of flags and compilers. Thanks for the heads-up, though.

**Comment by mid-kid** [comment]
Yep, this was fixed. Feel free to close.

**Comment by fabianhjr** [comment]
> > Heck for all we know you'll start hitting this issue in some build environments eventually too.
> I don't think this will happen in near two years as CentOS 7 doesn't have newer compilers 

I hit this on a nixpkgs/NixOS gcc-12 branch, while it still isn't merged I think it is feasible nixpkgs/NixOS could move to gcc-12 by default during the next 6 months.

**Comment by ilya-fedin** [comment]
This PR won't be merged

**Pull request closed without merging**
